import { Metadata } from "next";
import { LegalPageLayout } from "@/components/common/LegalPageLayout";
import { AlertTriangle } from "lucide-react";

export const metadata: Metadata = {
  title: "Clinical & Research Disclaimer",
  description:
    "Scientific disclaimer regarding the investigational nature of hybrid quantum machine learning algorithms in healthcare.",
};

export default function DisclaimerPage() {
  return (
    <LegalPageLayout
      title="Clinical & Research Disclaimer"
      subtitle="Critical regulatory disclosures regarding the investigational status of quantum variational classifiers and statistical benchmarking in clinical medicine."
      badge="Regulatory Disclosures"
      iconType="shield"
    >
      <div className="rounded-2xl border border-amber-300 bg-amber-50/80 p-6 text-[#082827] space-y-2 shadow-xs">
        <div className="flex items-center gap-2 font-mono text-xs uppercase tracking-widest text-amber-800 font-bold">
          <AlertTriangle size={15} />
          <span>Non-Diagnostic Regulatory Status</span>
        </div>
        <p className="text-sm leading-relaxed text-[#5A7470]">
          QureSight is an exploratory computational platform developed for academic research, algorithm validation, and comparative benchmarking between classical machine learning ensembles and parameterized quantum circuits. It is not an FDA-cleared diagnostic device.
        </p>
      </div>

      <section className="space-y-4">
        <h2 className="text-xl sm:text-2xl font-sans font-bold text-[#082827] border-b border-[#DFEBE8] pb-2.5">
          1. No Medical Advice or Treatment Recommendations
        </h2>
        <p>
          The risk probabilities, classification predictions (e.g., Benign vs. Malignant), and feature attributions generated by QureSight do not constitute formal medical diagnoses, clinical prognoses, or personalized therapeutic prescriptions. Healthcare providers must evaluate patient conditions using established standard-of-care clinical tests, biopsies, and radiographic imaging.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl sm:text-2xl font-sans font-bold text-[#082827] border-b border-[#DFEBE8] pb-2.5">
          2. Probabilistic &amp; Noisy Intermediate-Scale Quantum (NISQ) Realities
        </h2>
        <p>
          Quantum machine learning algorithms executed on current NISQ physical processors are inherently susceptible to environmental decoherence, thermal relaxation and two-qubit gate crosstalk. Although QureSight incorporates Zero-Noise Extrapolation (ZNE) and M3 readout error mitigation:
        </p>
        <ul className="list-disc pl-6 space-y-2 text-[#5A7470]">
          <li>
            Hardware shot variance may cause minor fluctuations in expectation values.
          </li>
          <li>
            All comparative claims are rigorously subjected to McNemar&apos;s test and Wilcoxon signed-rank tests with p &lt; 0.05 thresholding to prevent premature claims of quantum advantage.
          </li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl sm:text-2xl font-sans font-bold text-[#082827] border-b border-[#DFEBE8] pb-2.5">
          3. Clinician-in-the-Loop Requirement
        </h2>
        <p>
          Any translational research finding or biomarker attribution derived from QureSight&apos;s explainability modules must be independently reviewed by a qualified medical oncologist, pathologist, or geneticist prior to publication or clinical trial consideration.
        </p>
      </section>
    </LegalPageLayout>
  );
}
