import PageHeader from '@/components/PageHeader'

export default function DocsPage() {
  return (
    <div className="p-8 max-w-4xl">
      <PageHeader title="Documentation" subtitle="Platform reference and guidelines" />
      
      <div className="space-y-8 text-[#d1d5db]">
        <section className="bg-[#111827] border border-[#1f2937] p-6 rounded-lg">
          <h2 className="text-xl font-bold text-white mb-4">What is QureSight?</h2>
          <p className="mb-4">
            QureSight is a research prototype platform combining classical machine learning with 
            quantum machine learning (QML) for biomedical data analysis and disease-risk detection.
          </p>
          <p>
            The platform provides an end-to-end pipeline: data loading, preprocessing, model training, 
            benchmarking, explainability, and single-sample prediction.
          </p>
        </section>

        <section className="bg-[#111827] border border-[#1f2937] p-6 rounded-lg">
          <h2 className="text-xl font-bold text-white mb-4">Quantum Methods</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>VQC (Variational Quantum Classifier):</strong> Uses a parameterized quantum circuit as a machine learning model.</li>
            <li><strong>QSVM (Quantum Support Vector Machine):</strong> Uses a quantum circuit to compute a kernel matrix for an SVM.</li>
          </ul>
          <div className="mt-4 p-3 bg-blue-900/20 border border-blue-800/30 text-blue-200 rounded text-sm">
            Note: All quantum models currently run on simulators (PennyLane default.qubit) and do not use physical quantum hardware.
          </div>
        </section>

        <section className="bg-[#111827] border border-[#1f2937] p-6 rounded-lg">
          <h2 className="text-xl font-bold text-white mb-4">Explainability Methods</h2>
          <p className="mb-4">
            We use SHAP (SHapley Additive exPlanations) for local explainability of classical models.
            For quantum models, we use parameter shift rules and gradient-based sensitivity analysis 
            to determine feature importance.
          </p>
        </section>

        <section className="bg-red-900/20 border border-red-800/30 p-6 rounded-lg">
          <h2 className="text-xl font-bold text-red-400 mb-4">Medical Disclaimer</h2>
          <p className="text-red-200 text-sm">
            QureSight is a strictly educational and research prototype. The predictions, insights, 
            and explanations generated by this platform are not validated for clinical use and must 
            not be used for medical diagnosis, treatment, or decision-making. Always consult a qualified 
            healthcare professional for medical advice.
          </p>
        </section>
      </div>
    </div>
  )
}
